-- MySQL Script generated by MySQL Workbench
-- mar 15 may 2018 17:35:04 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema un_aventon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema un_aventon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `un_aventon` DEFAULT CHARACTER SET utf8 ;
USE `un_aventon` ;

-- -----------------------------------------------------
-- Table `un_aventon`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `asientos` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `patente` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehiculo_tipo1_idx` (`tipo_id` ASC),
  CONSTRAINT `fk_vehiculo_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `un_aventon`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`usuario_has_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`usuario_has_vehiculo` (
  `usuarios_id` INT NOT NULL,
  `vehiculo_id` INT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `vehiculo_id`),
  INDEX `fk_usuarios_has_vehiculo_vehiculo1_idx` (`vehiculo_id` ASC),
  INDEX `fk_usuarios_has_vehiculo_usuarios_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_usuarios_has_vehiculo_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_vehiculo_vehiculo1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `un_aventon`.`vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`viaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `precio` INT NOT NULL,
  `duracion` TINYINT NOT NULL,
  `distancia` INT NOT NULL,
  `lugares` TINYINT NOT NULL,
  `comentarios` TEXT NOT NULL,
  `id_origen` INT NOT NULL,
  `id_destino` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `vehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_viaje_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_viaje_vehiculo1_idx` (`vehiculo_id` ASC),
  INDEX `fk_viaje_ciudad1_idx` (`id_origen` ASC),
  INDEX `fk_viaje_ciudad2_idx` (`id_destino` ASC),
  CONSTRAINT `fk_viaje_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_vehiculo1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `un_aventon`.`vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_ciudad1`
    FOREIGN KEY (`id_origen`)
    REFERENCES `un_aventon`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_ciudad2`
    FOREIGN KEY (`id_destino`)
    REFERENCES `un_aventon`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`pregunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pregunta` TEXT NOT NULL,
  `viaje_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pregunta_viaje1_idx` (`viaje_id` ASC),
  INDEX `fk_pregunta_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_pregunta_viaje1`
    FOREIGN KEY (`viaje_id`)
    REFERENCES `un_aventon`.`viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`respuesta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `respuesta` TEXT NOT NULL,
  `pregunta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_respuesta_pregunta1_idx` (`pregunta_id` ASC),
  CONSTRAINT `fk_respuesta_pregunta1`
    FOREIGN KEY (`pregunta_id`)
    REFERENCES `un_aventon`.`pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`usuario_viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`usuario_viaje` (
  `usuarios_id` INT NOT NULL,
  `viaje_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_has_viaje_viaje1_idx` (`viaje_id` ASC),
  INDEX `fk_usuarios_has_viaje_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_usuarios_has_viaje_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_viaje_viaje1`
    FOREIGN KEY (`viaje_id`)
    REFERENCES `un_aventon`.`viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`viaje_ocasional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`viaje_ocasional` (
  `viaje_id` INT NOT NULL,
  `hora_salida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`viaje_id`),
  CONSTRAINT `fk_viaje_ocasional_viaje1`
    FOREIGN KEY (`viaje_id`)
    REFERENCES `un_aventon`.`viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`viaje_periodico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`viaje_periodico` (
  `viaje_id` INT NOT NULL AUTO_INCREMENT,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`viaje_id`),
  CONSTRAINT `fk_table1_viaje1`
    FOREIGN KEY (`viaje_id`)
    REFERENCES `un_aventon`.`viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`dia_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`dia_horario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(45) NOT NULL,
  `viaje_periodico_viaje_id` INT NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dia_horario_viaje_periodico1_idx` (`viaje_periodico_viaje_id` ASC),
  CONSTRAINT `fk_dia_horario_viaje_periodico1`
    FOREIGN KEY (`viaje_periodico_viaje_id`)
    REFERENCES `un_aventon`.`viaje_periodico` (`viaje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`calificacion_piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`calificacion_piloto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `puntuacion` TINYINT NOT NULL,
  `comentarios` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `piloto_id` INT NOT NULL,
  `copiloto_califica` INT NOT NULL,
  `viaje_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calificacion_piloto_usuarios1_idx` (`piloto_id` ASC),
  INDEX `fk_calificacion_piloto_usuarios2_idx` (`copiloto_califica` ASC),
  INDEX `fk_calificacion_piloto_viaje1_idx` (`viaje_id` ASC),
  CONSTRAINT `fk_calificacion_piloto_usuarios1`
    FOREIGN KEY (`piloto_id`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_piloto_usuarios2`
    FOREIGN KEY (`copiloto_califica`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_piloto_viaje1`
    FOREIGN KEY (`viaje_id`)
    REFERENCES `un_aventon`.`viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`calificacion_piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`calificacion_piloto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `puntuacion` TINYINT NOT NULL,
  `comentarios` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `piloto_id` INT NOT NULL,
  `copiloto_califica` INT NOT NULL,
  `viaje_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calificacion_piloto_usuarios1_idx` (`piloto_id` ASC),
  INDEX `fk_calificacion_piloto_usuarios2_idx` (`copiloto_califica` ASC),
  INDEX `fk_calificacion_piloto_viaje1_idx` (`viaje_id` ASC),
  CONSTRAINT `fk_calificacion_piloto_usuarios1`
    FOREIGN KEY (`piloto_id`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_piloto_usuarios2`
    FOREIGN KEY (`copiloto_califica`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_piloto_viaje1`
    FOREIGN KEY (`viaje_id`)
    REFERENCES `un_aventon`.`viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `un_aventon`.`calificacion_copiloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `un_aventon`.`calificacion_copiloto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `puntuacion` TINYINT NOT NULL,
  `comentarios` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `copiloto_id` INT NOT NULL,
  `viaje_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calificacion_copiloto_usuarios1_idx` (`copiloto_id` ASC),
  INDEX `fk_calificacion_copiloto_viaje1_idx` (`viaje_id` ASC),
  INDEX `fk_calificacion_copiloto_usuarios2_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_calificacion_copiloto_usuarios1`
    FOREIGN KEY (`copiloto_id`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_copiloto_viaje1`
    FOREIGN KEY (`viaje_id`)
    REFERENCES `un_aventon`.`viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_copiloto_usuarios2`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `un_aventon`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
